server:
  port: 8888
spring:
  application:
    name: spring-boot-demo
#  mvc:
#    pathmatch:
#      use-suffix-pattern: false
#      use-registered-suffix-pattern: true
#    contentnegotiation:
#      favor-path-extension: true

#Logback配置
logging:
  file:
    path: /var/log
    name: /var/log/demo.log
    max-history: 1
  pattern:
    console: "%d [%thread] %-5level %40logger{40} - %msg%n"
    file: "%d [%thread] %-5level %40logger{40} - %msg%n"
    level: DEBUG
    rolling-file-name: "/var/log/archive/demo.%d{yyyy-MM-dd}.%i.gz"
