server:
  port: 8888
spring:
  application:
    name: spring-boot-demo
logging:
  file:
    path: /var/log/
    name: demo.log
    max-history: 1
  pattern:
    console: %d [%thread] %-5level %40logger{40} - %msg%n
    level: DEBUG
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz)
